### ISSUE TITLE
Vehicle shops

### ISSUE THREAD

**Issue by Pump-Codes** [Magnom96/resources#2]
Vehicle shop commands such as finance and enablebuy do not work

**Comment by Magnom96** [comment]
> Vehicle shop commands such as finance and enablebuy do not work

They do, Finance I believe only works at PDM, and enablebuy doesn't show, just hit G and it will work.

**Comment by Pump-Codes** [comment]
Just says you need a sales rep, even though I have the job and I enabledbuy

**Comment by Magnom96** [comment]
Not really sure what to tell you, I've never had a problem with ith

**Comment by Pump-Codes** [comment]
What is the command format to setjob

**Comment by Magnom96** [comment]
> What is the command format to setjob

It's done in the database.
